#!/bin/bash
#变量定义
#m1=0;
m_1="apt-get install gcc";
#m2=0;
m_2="apt-get install build-essential";
#m3=0;
m_3="apt-get install make";
#m4=0;
m_4="apt-get install gdb";
#执行语句
if apt-get install gcc
then
m1=1;
echo "sucess!"
else
echo "defeated!"
fi
if apt-get install build-essential
then
m2=1;
echo "sucess!"
else
echo "defeated!"
fi
if apt-get install make
then
m3=1;
echo "sucess!"
else
echo "defeated!"
fi
if apt-get install gdb
then
m4=1;
echo "sucess!"
else
echo "defeated!"
fi
#变量处理部分
#1
if [ $m1 -ne 0 ]
then
echo "$m_1 sucess!"
else
echo "$m_1 fefeated!"
fi
#2
if [ $m2 -ne 0 ]
then
echo "$m_2 sucess!"
else
echo "$m_2 fefeated!"
fi
#3
if [ $m3 -ne 0 ]
then
echo "$m_3 sucess!"
else
echo "$m_3 fefeated!"
fi
#4
if [ $m4 -ne 0 ]
then
echo "$m_4 sucess!"
else
echo "$m_4 fefeated!"
fi

